/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* CapSense_ISR */
#define CapSense_ISR__INTC_CORTEXM0P_ASSIGNED 1
#define CapSense_ISR__INTC_CORTEXM0P_MUX 8u
#define CapSense_ISR__INTC_CORTEXM0P_PRIORITY 3u
#define CapSense_ISR__INTC_CORTEXM4_ASSIGNED 1
#define CapSense_ISR__INTC_CORTEXM4_PRIORITY 7u
#define CapSense_ISR__INTC_NUMBER 49u
#define CapSense_ISR_INTC_CORTEXM0P_ASSIGNED 1
#define CapSense_ISR_INTC_CORTEXM0P_MUX 8u
#define CapSense_ISR_INTC_CORTEXM0P_PRIORITY 3u
#define CapSense_ISR_INTC_CORTEXM4_ASSIGNED 1
#define CapSense_ISR_INTC_CORTEXM4_PRIORITY 7u
#define CapSense_ISR_INTC_NUMBER 49u

/* BLE_1_bless_isr */
#define BLE_1_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_1_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_1_bless_isr__INTC_CORTEXM0P_PRIORITY 3u
#define BLE_1_bless_isr__INTC_CORTEXM4_ASSIGNED 1
#define BLE_1_bless_isr__INTC_CORTEXM4_PRIORITY 7u
#define BLE_1_bless_isr__INTC_NUMBER 24u
#define BLE_1_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_1_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_1_bless_isr_INTC_CORTEXM0P_PRIORITY 3u
#define BLE_1_bless_isr_INTC_CORTEXM4_ASSIGNED 1
#define BLE_1_bless_isr_INTC_CORTEXM4_PRIORITY 7u
#define BLE_1_bless_isr_INTC_NUMBER 24u

/* DEBUG_UART_SCB_IRQ */
#define DEBUG_UART_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define DEBUG_UART_SCB_IRQ__INTC_CORTEXM0P_MUX 9u
#define DEBUG_UART_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define DEBUG_UART_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define DEBUG_UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define DEBUG_UART_SCB_IRQ__INTC_NUMBER 46u
#define DEBUG_UART_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define DEBUG_UART_SCB_IRQ_INTC_CORTEXM0P_MUX 9u
#define DEBUG_UART_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define DEBUG_UART_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define DEBUG_UART_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define DEBUG_UART_SCB_IRQ_INTC_NUMBER 46u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
